---
name: hosted-ninja-vcpkg_submod
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.driver }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { driver: azure, os: ubuntu-latest, triplet: x64-linux, dbg_preset: azure-ninja-dbg, rel_preset: azure-ninja-rel }
          - { driver: azure, os: macos-latest, triplet: arm64-osx, dbg_preset: azure-ninja-dbg, rel_preset: azure-ninja-rel }
          - { driver: azure, os: macos-15-intel, triplet: x64-osx, dbg_preset: azure-ninja-dbg, rel_preset: azure-ninja-rel }
          - { driver: azure, os: macos-14, triplet: arm64-osx, dbg_preset: azure-ninja-dbg, rel_preset: azure-ninja-rel }
          - { driver: azure, os: windows-latest, triplet: x64-windows-static, dbg_preset: azure-ninja-dbg, rel_preset: azure-ninja-rel }
          - { driver: gcs, os: ubuntu-latest, triplet: x64-linux, dbg_preset: gcs-ninja-dbg, rel_preset: gcs-ninja-rel }
          - { driver: gcs, os: macos-latest, triplet: arm64-osx, dbg_preset: gcs-ninja-dbg, rel_preset: gcs-ninja-rel }
          - { driver: gcs, os: macos-15-intel, triplet: x64-osx, dbg_preset: gcs-ninja-dbg, rel_preset: gcs-ninja-rel }
          - { driver: gcs, os: macos-14, triplet: arm64-osx, dbg_preset: gcs-ninja-dbg, rel_preset: gcs-ninja-rel }
          - { driver: gcs, os: windows-latest, triplet: x64-windows-static, dbg_preset: gcs-ninja-dbg, rel_preset: gcs-ninja-rel }
          - { driver: s3, os: ubuntu-latest, triplet: x64-linux, dbg_preset: s3-ninja-dbg, rel_preset: s3-ninja-rel }
          - { driver: s3, os: macos-latest, triplet: arm64-osx, dbg_preset: s3-ninja-dbg, rel_preset: s3-ninja-rel }
          - { driver: s3, os: macos-15-intel, triplet: x64-osx, dbg_preset: s3-ninja-dbg, rel_preset: s3-ninja-rel }
          - { driver: s3, os: macos-14, triplet: arm64-osx, dbg_preset: s3-ninja-dbg, rel_preset: s3-ninja-rel }
          - { driver: s3, os: windows-latest, triplet: x64-windows, dbg_preset: s3-ninja-dbg, rel_preset: s3-ninja-rel }
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      id-token: write
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AZURE_DRIVER_LOGLEVEL: trace
      GCS_DRIVER_LOGLEVEL: trace
      S3_DRIVER_LOGLEVEL: trace

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./.github/actions/fix-win-azure-config
        if: matrix.driver == 'azure'

      - uses: lukka/get-cmake@v3.30.3

      - name: Restore from cache and setup vcpkg executable and data files
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '${{ matrix.driver }}/vcpkg.json'
          vcpkgDirectory: '${{ matrix.driver }}/vcpkg'

      - name: Install Azurite
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        id: azuright
        uses: sgouache/azuright@v1.2
        with:
          skip-api-version-check: true

      - name: Set Azure test prefixes
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        run: |
          EMULATED_BLOB_ENDPOINT=$(echo '${{ steps.azuright.outputs.connstring }}' | tr ';' '\n' | grep -E '^BlobEndpoint=' | cut -d'=' -f2)
          echo "STORAGE_DRIVER_TEST_URL_PREFIX_EMULATED_BLOB=$EMULATED_BLOB_ENDPOINT/data-test-khiops-driver-azure" >> "$GITHUB_ENV"

      - name: Populate Azurite with test data
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          export AZURE_STORAGE_CONNECTION_STRING='${{ steps.azuright.outputs.connstring }}'
          az storage container create -n data-test-khiops-driver-azure --connection-string "${{ steps.azuright.outputs.connstring }}"
          az storage blob upload-batch --destination data-test-khiops-driver-azure/khiops_data --source "$PWD/azure/khiops_data" --connection-string "${{ steps.azuright.outputs.connstring }}"

      - uses: google-github-actions/auth@v2
        if: matrix.driver == 'gcs'
        with:
          service_account: 'khiops-gcs-driver-test-sa@ino-olr-dak-ideal-sbx.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/322269704080/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Install coverage tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov gcovr

      - name: Build debug
        if: matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.dbg_preset }}'
          configurePresetAdditionalArgs: '["-DBUILD_TESTS=ON"]'
          buildPreset: '${{ matrix.dbg_preset }}'

      - name: Test debug with emulated Azure blob storage
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          testPreset: '${{ matrix.dbg_preset }}'
        env:
          AZURE_EMULATED_STORAGE: 'true'
          AZURE_STORAGE_CONNECTION_STRING: '${{ steps.azuright.outputs.connstring }}'
          STORAGE_DRIVER_TEST_URL_PREFIX: '${{ env.STORAGE_DRIVER_TEST_URL_PREFIX_EMULATED_BLOB }}'

      - name: Test debug with Azure cloud blob storage
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'azure-ninja-dbg-blob'
        env:
          AZURE_EMULATED_STORAGE: 'false'
          AZURE_STORAGE_CONNECTION_STRING: '${{ secrets.AZURE_CONNECTION_STRING }}'
          CTEST_PARALLEL_LEVEL: ''

      - name: Test debug with Azure cloud file storage
        if: matrix.driver == 'azure' && matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'azure-ninja-dbg-file'
        env:
          AZURE_EMULATED_STORAGE: 'false'
          AZURE_STORAGE_CONNECTION_STRING: '${{ secrets.AZURE_CONNECTION_STRING }}'
          CTEST_PARALLEL_LEVEL: ''

      - name: Test debug
        if: matrix.driver != 'azure' && matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v10
        with:
          testPreset: '${{ matrix.dbg_preset }}'
        env:
          CTEST_PARALLEL_LEVEL: ''

      - name: Build release
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.rel_preset }}'
          configurePresetAdditionalArgs: '["-DBUILD_TESTS=ON"]'
          buildPreset: '${{ matrix.rel_preset }}'

      - uses: azure/login@v2.3.0
        if: matrix.driver == 'azure' && github.ref_type != 'tag'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Use Azure connection string on tags
        if: matrix.driver == 'azure' && github.ref_type == 'tag'
        run: echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}" >> "$GITHUB_ENV"

      - name: Test release with Azure blob storage
        if: matrix.driver == 'azure'
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'azure-ninja-rel-blob'
          testPresetAdditionalArgs: '["--output-junit", "test_results_blob.xml"]'
        env:
          CTEST_PARALLEL_LEVEL: ''

      - name: Test release with Azure file storage
        if: matrix.driver == 'azure'
        uses: lukka/run-cmake@v10
        with:
          testPreset: 'azure-ninja-rel-file'
          testPresetAdditionalArgs: '["--output-junit", "test_results_file.xml"]'
        env:
          CTEST_PARALLEL_LEVEL: ''

      - name: Test release
        if: matrix.driver != 'azure'
        uses: lukka/run-cmake@v10
        with:
          testPreset: '${{ matrix.rel_preset }}'
          testPresetAdditionalArgs: '["--output-junit", "test_results.xml"]'
        env:
          CTEST_PARALLEL_LEVEL: ''

      - name: Upload Azure test summaries
        if: matrix.driver == 'azure' && always()
        uses: test-summary/action@v2
        with:
          paths: |
            ${{ github.workspace }}/build/azure/${{ matrix.rel_preset }}/test_results_blob.xml
            ${{ github.workspace }}/build/azure/${{ matrix.rel_preset }}/test_results_file.xml

      - name: Upload test summary
        if: matrix.driver != 'azure' && always()
        uses: test-summary/action@v2
        with:
          paths: ${{ github.workspace }}/build/${{ matrix.driver }}/${{ matrix.rel_preset }}/test_results.xml

      - name: Upload built libraries
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.driver }}-${{ matrix.os }}
          path: |
            build/${{ matrix.driver }}/${{ matrix.rel_preset }}/lib/*.dylib
            build/${{ matrix.driver }}/${{ matrix.rel_preset }}/lib/*.so
            build/${{ matrix.driver }}/${{ matrix.rel_preset }}/bin/*.dll
            build/${{ matrix.driver }}/${{ matrix.rel_preset }}/bin/*.lib
          if-no-files-found: ignore